### ISSUE TITLE
Demo or Image to preview

### ISSUE THREAD

**Issue by ftonato** [es6rocks/harmonic-theme-selfblog#15]
Would be nice if you could provide a live demo or a simple image to preview!

**Comment by jaydson** [comment]
What do you mean @ftonato ?
You can build a demo website with this theme, so you can see what is happening

Basically, clone this repo

``` shell
git clone git@github.com:JSRocksHQ/harmonic-theme-selfblog.git
```

Create and build a demo website with Harmonic:

``` shell
harmonic init "demo_website"
cd demo_website
npm install
```

Ah, you'll need to install the theme on your project:

``` shell
cd demo_website
npm install ../harmonic-theme-selfblog
```

Then, just run:

``` shell
harmonic run
```

**Comment by UltCombo** [comment]
`harmonic-theme-selfblog` will be the theme for Harmonic's website itself. You will be able to see a live demo at http://harmonicjs.com/ when it is released. :smile:

**Comment by ftonato** [comment]
The idea/suggestion was just to see the online demo, without downloading :sweat_smile:

**Comment by robsongajunior** [comment]
The harmonic website it is not all ready yet. Without downloading project is not possible a preview.

**Comment by UltCombo** [comment]
There will be a live demo when http://harmonicjs.com/ goes live. :stuck_out_tongue:

**Comment by ftonato** [comment]
Okay, We may close this issue. :v:
