### ISSUE TITLE
Incorrect font-weight

### ISSUE THREAD

**Issue by viniciusdacal** [es6rocks/harmonic-theme-selfblog#16]
In some places the font used is 'nexa_boldregular' instead of 'nexa_lightregular' as in PSD file.
Does it have to change or it's that way in purpose?

**Comment by viniciusdacal** [comment]
I saw some differences comparing the colors from layout with the .PSD too. I'm going to send a pull request with these fixes.
If there is a reason to It be like it's  right now, just ignore ;)

**Comment by robsongajunior** [comment]
thanks @viniciusdacal.
fixed
