### ISSUE TITLE
Add template to "Let us know" link

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic-theme-selfblog#22]
It would be better to use `issues/new?title=...&body...` URL format: [example](https://github.com/babel/babel.github.io/issues/new?title=New+User%3A+%5Binsert+name%5D%0A&body=Please+fill+the+following+out%3A%0A%0A-+Name%3A+%28correctly+formatted%29%0A-+Homepage+url%3A+%28homepage%2Fprimary+entry+point+for+users%29%0A-+Brand+Guidelines%2FLicensing%3A+%28or+anything+we+need+to+know+before+using+your+logo%29%0A-+Logo%3A+%28svg+if+possible%2C+pngs+over+500x200px+with+transparent+backgrounds+are+also+acceptable%29%0A%0A%3E+Example%3A%0A%3E%0A%3E+Name%3A+CloudFlare%0A%3E+Homepage+url%3A+https%3A%2F%2Fcloudflare.com%0A%3E+Brand+Guidelines%2FLicensing%3A+https%3A%2F%2Fwww.cloudflare.com%2Flogo%0A%3E+Logo%3A+https%3A%2F%2Fwww.cloudflare.com%2Fmedia%2Fdownloads%2Fcloudflare-logo-kit.zip%0A).

**Comment by UltCombo** [comment]
cc @jaydson @robsongajunior

**Comment by jaydson** [comment]
Awesome ~stolen~ idea @UltCombo :smile:

**Comment by UltCombo** [comment]
"Code reuse":exclamation:

**Comment by jaydson** [comment]
:facepunch: :+1:

**Comment by robsongajunior** [comment]
:+1:
woow oO good idea @UltCombo

**Comment by mateusortiz** [comment]
I just created the issue [template](https://github.com/jsrockshq/harmonic/issues/new?title=New+Case%3A+%5Binsert+name%5D%0A&body=Please+fill+the+following+out%3A%0A%0A-+Name%3A+%28correctly+formatted%29%0A-+Homepage+url%3A+%28homepage%2Fprimary+entry+point+for+users%29%0A-+Logo%3A+%28svg+if+possible%2C+pngs+over+330x175px+with+transparent+backgrounds+are+also+acceptable%29%0A%0A%3E+Example%3A%0A%3E%0A%3E+Name%3A+JSRocks%0A%3E+Homepage+url%3A+http%3A%2F%2Fjsrocks.org%0A%3E+Logo%3A+http%3A%2F%2Fwww.jsrocks.org%2Fimages%2Flogo.svg%0A), what do you think?

**Comment by UltCombo** [comment]
@mateusortiz Nice! perhaps "New showcase" instead of "new case" would be more clear?

**Comment by mateusortiz** [comment]
@UltCombo Yeap, I will update :smile:

**Comment by UltCombo** [comment]
Perhaps a "Short description" field would be nice too, since the [homepage](http://harmonicjs.com/) uses it.

**Comment by mateusortiz** [comment]
now with all the changes made to the [template](https://github.com/jsrockshq/harmonic/issues/new?title=New+showcase%3A+%5Binsert+name%5D%0A&body=Please+fill+the+following+out%3A%0A%0A-+Name%3A+%28correctly+formatted%29%0A-+Homepage+url%3A+%28homepage%2Fprimary+entry+point+for+users%29%0A-+Short+description%3A+%28short+description+of+the+project%29%0A-+Logo%3A+%28svg+if+possible%2C+pngs+over+330x175px+with+transparent+backgrounds+are+also+acceptable%29%0A%0A%3E+Example%3A%0A%3E%0A%3E+Name%3A+JSRocks%0A%3E+Homepage+url%3A+http%3A%2F%2Fjsrocks.org%0A%3E+Description%3A+A+collaborative+website+about+the+ECMAScript+sixth+edition%0A%3E+Logo%3A+http%3A%2F%2Fwww.jsrocks.org%2Fimages%2Flogo.svg%0A)

**Comment by UltCombo** [comment]
AWESOME! :smile: 
Can you commit it or send a PR?

**Comment by mateusortiz** [comment]
I just sent :sparkles:

**Comment by UltCombo** [comment]
Nice work! :+1: 
@jaydson can you re-deploy the site?

**Comment by robsongajunior** [comment]
Great, good job. Sorry for delay.

Thanks @mateusortiz @UltCombo

**Comment by UltCombo** [comment]
I think we can close this issue now.
@jaydson @robsongajunior please re-deploy the site. :smiley:
