### ISSUE TITLE
import updates from website's readme

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/harmonic-theme-selfblog#25]
https://github.com/JSRocksHQ/harmonic-website/commit/28e7ff4f758e31c971f3a67c705baff1ed3da636

**Comment by robsongajunior** [comment]
: D

**Comment by UltCombo** [comment]
@robsongajunior can you reference the commit where you've pulled the updates from the [site's readme](https://github.com/JSRocksHQ/harmonic-website/commit/28e7ff4f758e31c971f3a67c705baff1ed3da636) to this theme's contents?

**Comment by robsongajunior** [comment]
(Y)

**Comment by UltCombo** [comment]
Please re-read this issue's title.
It is asking to import the updates from the [linked commit](https://github.com/JSRocksHQ/harmonic-website/commit/28e7ff4f758e31c971f3a67c705baff1ed3da636) to this repository's contents.
Both contain the same text, so when one is updated the other should be updated as well.

**Comment by UltCombo** [comment]
The typos had already been fixed in separate commits, so there was actually very little to import.
