### ISSUE TITLE
Text intro

### ISSUE THREAD

**Issue by jaydson** [es6rocks/harmonic-theme-selfblog#7]
> Harmonic is yet another JavaScript static website generator, but mordern.
> Harmonic's core is built using the latest JavaScript features.
> By using the ECMA-262 Standard we're helping the JavaScript language to envolve and also learning how to play with.
> Besides that Harmonic actually does the "static website generator" jpb pretty well. 

Change to: 
Harmonic is yet another JavaScript static website generator, but modern.
Harmonic's core is built using the latest JavaScript features.
By using the ECMA-262 Standard we're helping the language to envolve and also learning how to play with.
Besides that, Harmonic actually does the "static website generator" job pretty well.

**Comment by UltCombo** [comment]
Typo:
envolve -> evolve

Suggestion:
play with. -> play with it.

**Comment by viniciusdacal** [comment]
this was fixed here f1f9c23

**Comment by robsongajunior** [comment]
Right, thanks @viniciusdacal
