### ISSUE TITLE
Text Painless blogging

### ISSUE THREAD

**Issue by jaydson** [es6rocks/harmonic-theme-selfblog#8]
> As usual a static website generator, you can focus on your content. Just write some markdown files and Harmonic will take care of everything, including pages, articles, categories and themes.

Change to:
As usual in a static website generator, you can focus on your content. Just write some markdown files and Harmonic will take care of everything, including pages, articles, categories and themes.

You can validate the text in this issue: https://github.com/JSRocksHQ/harmonic/issues/128

**Comment by robsongajunior** [comment]
fixed
